version: "3.5"
services:
  database:
    container_name: postgresdb
    image: postgres:13-alpine
    ports:
      - 5440:5432
    env_file:
      - postgres.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
    restart: unless-stopped
    # networks:
    #   - api-network

  ts-api:
    depends_on:
      - database
    container_name: rad-api-typescript
    image: rad-api:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - NODE_PORT=${NODE_PORT}
    ports:
      - ${DOCKER_EXPOSE_PORT}:${NODE_PORT}
    restart: always
    # networks:
    #   - api-network
# networks:
#   api-network:
